"""Master taxonomy of 200+ investment themes with descriptions for embedding."""

# Each theme has a short keyword-rich description used for sentence-transformer embedding.
# Format: {theme_name: description_for_embedding}
THEME_DESCRIPTIONS: dict[str, str] = {
    # --- Technology ---
    "artificial intelligence": "AI machine learning deep learning neural networks generative AI LLM",
    "machine learning": "ML predictive models training data algorithms supervised unsupervised",
    "cloud computing": "cloud SaaS PaaS IaaS infrastructure as a service AWS Azure GCP",
    "cybersecurity": "cybersecurity data protection encryption threat detection security software",
    "big data": "big data analytics data-driven data warehouse data lake business intelligence",
    "blockchain": "blockchain distributed ledger smart contracts decentralized Web3",
    "quantum computing": "quantum computing qubit quantum advantage quantum supremacy",
    "semiconductors": "semiconductor chip design fabrication wafer foundry integrated circuit",
    "software": "software development enterprise SaaS application platform engineering",
    "5g": "5G wireless fifth generation mobile network mmWave sub-6 telecommunications",
    "internet of things": "IoT connected devices smart sensors edge computing M2M",
    "edge computing": "edge computing distributed processing low-latency real-time inference",
    "augmented reality": "AR augmented reality mixed reality spatial computing overlay",
    "virtual reality": "VR virtual reality immersive headset metaverse 3D simulation",
    "natural language processing": "NLP text analysis sentiment analysis language model chatbot",
    "computer vision": "computer vision image recognition object detection visual AI",
    "robotic process automation": "RPA process automation workflow bots digital workers",
    "devops": "DevOps CI/CD continuous integration deployment infrastructure automation",
    "low-code platforms": "low-code no-code citizen developer visual programming rapid development",
    "api economy": "API economy integration microservices platform connectivity",
    "digital twin": "digital twin simulation virtual model predictive maintenance",
    # --- Digital Economy ---
    "e-commerce": "e-commerce online retail digital marketplace online shopping",
    "fintech": "fintech digital payment mobile payment neobank digital banking",
    "digital payments": "digital payments contactless NFC mobile wallet payment processing",
    "adtech": "advertising technology adtech digital advertising programmatic ad exchange",
    "social media": "social media platform user-generated content influencer engagement",
    "streaming": "streaming video on demand OTT content delivery media streaming",
    "gaming": "video game gaming esports game console game development",
    "mobile": "mobile device smartphone app mobile commerce tablet",
    "digital transformation": "digital transformation digitization modernization legacy migration",
    "creator economy": "creator economy content monetization influencer platform gig",
    "subscription economy": "subscription recurring revenue membership SaaS retention",
    "marketplace platform": "marketplace two-sided platform peer-to-peer matching",
    "sharing economy": "sharing economy ride-hailing rental peer-to-peer collaborative",
    "edtech": "education technology online learning LMS e-learning EdTech",
    "proptech": "property technology real estate tech smart building tenant management",
    "insurtech": "insurance technology insurtech claims automation underwriting",
    "regtech": "regulatory technology compliance automation KYC AML",
    "legaltech": "legal technology contract analysis document automation AI law",
    "foodtech": "food technology delivery meal kit ghost kitchen alternative protein",
    "traveltech": "travel technology booking platform hospitality tourism",
    # --- Healthcare & Life Sciences ---
    "healthcare": "healthcare medical hospital health system clinical care",
    "genomics": "genomics genome gene therapy CRISPR DNA sequencing precision medicine",
    "biotechnology": "biotechnology biotech biological drugs biopharmaceutical",
    "medical devices": "medical device diagnostic equipment surgical instrument implant",
    "telehealth": "telehealth telemedicine remote care virtual clinic digital health",
    "drug discovery": "drug discovery pharmaceutical clinical trial drug development pipeline",
    "precision medicine": "precision medicine personalized therapy targeted treatment biomarker",
    "digital health": "digital health health app wearable health monitoring remote patient",
    "mental health": "mental health wellness therapy behavioral health mindfulness",
    "healthcare ai": "healthcare AI clinical decision support medical imaging diagnosis",
    "longevity": "longevity anti-aging life extension geroscience senolytics",
    "synthetic biology": "synthetic biology bioengineering genetic engineering cell therapy",
    "medical robotics": "medical robotics surgical robot minimally invasive robotic surgery",
    "diagnostics": "diagnostics testing lab assay molecular diagnostic point-of-care",
    "vaccines": "vaccine immunization mRNA viral vector pandemic prevention",
    "rare diseases": "rare disease orphan drug genetic disorder unmet medical need",
    "cannabis": "cannabis marijuana CBD THC legalization dispensary",
    # --- Energy & Environment ---
    "renewable energy": "renewable energy clean energy green energy transition",
    "solar": "solar energy photovoltaic panel solar farm distributed generation",
    "wind energy": "wind energy turbine offshore wind onshore wind farm",
    "clean energy": "clean energy decarbonization zero emission carbon neutral",
    "electric vehicles": "electric vehicle EV battery charging station range",
    "battery technology": "battery lithium-ion solid-state energy storage cell",
    "hydrogen": "hydrogen fuel cell green hydrogen electrolysis H2",
    "carbon capture": "carbon capture CCS CCUS direct air capture sequestration",
    "sustainability": "sustainability ESG environmental social governance green",
    "cleantech": "cleantech clean technology environmental innovation green tech",
    "nuclear energy": "nuclear energy small modular reactor SMR fusion fission",
    "energy storage": "energy storage grid-scale battery pumped hydro flywheel",
    "smart grid": "smart grid utility modernization demand response distributed energy",
    "water technology": "water technology purification desalination wastewater treatment",
    "circular economy": "circular economy recycling waste reduction reuse upcycling",
    "carbon credits": "carbon credits offset trading emissions marketplace",
    "biofuels": "biofuels ethanol biodiesel renewable fuel biomass",
    "geothermal": "geothermal energy heat pump underground thermal",
    # --- Industrials & Infrastructure ---
    "robotics": "robotics robot automation industrial robot collaborative",
    "automation": "automation manufacturing process control PLC industrial IoT",
    "autonomous driving": "autonomous driving self-driving lidar ADAS driverless",
    "space": "space exploration launch satellite orbit rocket aerospace",
    "aerospace": "aerospace aviation aircraft defense military",
    "defense": "defense military weapons national security government contractor",
    "3d printing": "3D printing additive manufacturing rapid prototyping",
    "smart cities": "smart city urban technology connected infrastructure intelligent transport",
    "infrastructure": "infrastructure construction building bridge highway public works",
    "drones": "drone UAV unmanned aerial vehicle delivery inspection surveillance",
    "supply chain": "supply chain logistics freight shipping warehousing distribution",
    "advanced manufacturing": "advanced manufacturing Industry 4.0 smart factory CNC",
    "construction tech": "construction technology BIM prefab modular building",
    "last mile delivery": "last mile delivery courier parcel logistics fulfillment",
    "autonomous vehicles": "autonomous vehicle self-driving truck robotaxi fleet",
    "precision agriculture": "precision agriculture agtech farming sensor crop monitoring",
    # --- Consumer & Lifestyle ---
    "wearable technology": "wearable smartwatch fitness tracker health monitoring Apple Watch",
    "lifestyle": "lifestyle consumer brand premium ecosystem product design",
    "luxury": "luxury premium high-end fashion designer brand prestige",
    "pet economy": "pet economy animal care veterinary pet food pet tech",
    "wellness": "wellness health fitness nutrition supplement self-care",
    "beauty tech": "beauty technology cosmetics skincare personalized beauty",
    "smart home": "smart home connected home automation IoT thermostat security",
    "plant-based": "plant-based meat alternative protein vegan beyond impossible",
    "direct-to-consumer": "direct-to-consumer DTC brand e-commerce online retail",
    "athleisure": "athleisure activewear sportswear fitness fashion yoga",
    "connected fitness": "connected fitness Peloton home gym workout streaming wearable",
    "esports": "esports competitive gaming tournament streaming professional gaming",
    "metaverse": "metaverse virtual world digital avatar immersive social",
    "nft": "NFT non-fungible token digital collectible digital art marketplace",
    # --- Financial Services ---
    "banking": "banking retail bank commercial bank lending deposits",
    "insurance": "insurance underwriting claims actuarial risk management",
    "real estate": "real estate REIT property commercial residential",
    "cryptocurrency": "cryptocurrency crypto bitcoin ethereum digital asset",
    "defi": "DeFi decentralized finance yield farming liquidity protocol",
    "asset management": "asset management fund investment portfolio wealth",
    "wealth management": "wealth management private banking advisory high-net-worth",
    "payments infrastructure": "payments infrastructure rails clearing settlement ACH",
    "embedded finance": "embedded finance banking-as-a-service BaaS integrated financial",
    "open banking": "open banking API PSD2 data sharing financial aggregation",
    "credit scoring": "credit scoring alternative data underwriting risk assessment",
    "digital assets": "digital assets tokenization security token digital securities",
    "buy now pay later": "buy now pay later BNPL installment credit consumer financing",
    # --- Demographics & Society ---
    "aging population": "aging population elderly senior care retirement longevity",
    "millennial consumer": "millennial Gen Z digital native mobile-first social",
    "remote work": "remote work hybrid work-from-home distributed workforce collaboration",
    "gig economy": "gig economy freelance independent contractor on-demand platform",
    "urbanization": "urbanization urban growth city planning density migration",
    "diversity inclusion": "diversity inclusion equity belonging DEI representation",
    "digital identity": "digital identity verification biometric authentication KYC",
    "privacy": "privacy data protection GDPR consent personal data",
    # --- Materials & Resources ---
    "lithium": "lithium mining extraction battery raw material brine",
    "rare earth": "rare earth elements minerals critical materials supply chain",
    "copper": "copper mining electrical wiring conductor infrastructure",
    "gold": "gold mining precious metal bullion safe haven",
    "silver": "silver mining precious metal industrial solar panel",
    "uranium": "uranium mining nuclear fuel enrichment yellowcake",
    "steel": "steel manufacturing iron ore alloy construction",
    "aluminum": "aluminum smelting bauxite lightweight metal packaging",
    "cobalt": "cobalt mining battery cathode DRC supply chain",
    "nickel": "nickel mining stainless steel battery EV cathode",
    "timber": "timber forestry lumber wood products sustainable",
    "water resources": "water resources scarcity rights utility municipal",
    # --- Agriculture & Food ---
    "agriculture": "agriculture farming crop livestock agribusiness",
    "agtech": "agtech agricultural technology precision farming drone sensor",
    "vertical farming": "vertical farming indoor agriculture hydroponics controlled environment",
    "food safety": "food safety inspection traceability contamination testing",
    "food delivery": "food delivery meal platform restaurant ghost kitchen",
    "alternative protein": "alternative protein cultivated meat insect protein fermentation",
    # --- Telecom & Media ---
    "telecommunications": "telecommunications telecom carrier network fiber broadband",
    "fiber optics": "fiber optics broadband FTTH gigabit optical network",
    "satellite": "satellite communication LEO constellation Starlink internet",
    "media": "media entertainment content production studio broadcast",
    "music streaming": "music streaming audio podcast playlist subscription",
    "podcasting": "podcast audio content creator show advertising",
    "digital advertising": "digital advertising display search video programmatic",
    "content moderation": "content moderation trust safety policy AI detection",
    # --- Government & Public Sector ---
    "govtech": "government technology civic tech public sector digital",
    "defense tech": "defense technology military innovation weapons systems",
    "national security": "national security intelligence surveillance counterterrorism",
    "civic engagement": "civic engagement voting election democracy participation",
    # --- Cross-cutting themes ---
    "data center": "data center colocation server rack cooling hyperscale",
    "cloud infrastructure": "cloud infrastructure server GPU compute storage networking",
    "ai chips": "AI chips GPU TPU accelerator neural processing unit",
    "generative ai": "generative AI text-to-image language model creative AI GPT",
    "responsible ai": "responsible AI ethics bias fairness transparency explainability",
    "climate tech": "climate technology carbon reduction adaptation resilience",
    "impact investing": "impact investing ESG social return sustainable development",
    "femtech": "femtech women health fertility pregnancy menopause",
    "eldertech": "eldertech senior technology aging in place fall detection",
    "neurotechnology": "neurotechnology brain-computer interface neural implant cognitive",
    "bioprinting": "bioprinting tissue engineering organ 3D bioink",
    "nanotechnology": "nanotechnology nanomaterial nanoparticle nanoscale fabrication",
    "photonics": "photonics optical computing laser fiber optic silicon photonics",
}

# Category assignments
THEME_CATEGORIES: dict[str, str] = {
    # Technology
    **{t: "technology" for t in [
        "artificial intelligence", "machine learning", "cloud computing",
        "cybersecurity", "big data", "blockchain", "quantum computing",
        "semiconductors", "software", "5g", "internet of things",
        "edge computing", "augmented reality", "virtual reality",
        "natural language processing", "computer vision",
        "robotic process automation", "devops", "low-code platforms",
        "api economy", "digital twin",
    ]},
    # Digital Economy
    **{t: "digital economy" for t in [
        "e-commerce", "fintech", "digital payments", "adtech",
        "social media", "streaming", "gaming", "mobile",
        "digital transformation", "creator economy", "subscription economy",
        "marketplace platform", "sharing economy", "edtech", "proptech",
        "insurtech", "regtech", "legaltech", "foodtech", "traveltech",
    ]},
    # Healthcare
    **{t: "healthcare & life sciences" for t in [
        "healthcare", "genomics", "biotechnology", "medical devices",
        "telehealth", "drug discovery", "precision medicine", "digital health",
        "mental health", "healthcare ai", "longevity", "synthetic biology",
        "medical robotics", "diagnostics", "vaccines", "rare diseases", "cannabis",
    ]},
    # Energy
    **{t: "energy & environment" for t in [
        "renewable energy", "solar", "wind energy", "clean energy",
        "electric vehicles", "battery technology", "hydrogen",
        "carbon capture", "sustainability", "cleantech", "nuclear energy",
        "energy storage", "smart grid", "water technology",
        "circular economy", "carbon credits", "biofuels", "geothermal",
    ]},
    # Industrials
    **{t: "industrials & infrastructure" for t in [
        "robotics", "automation", "autonomous driving", "space",
        "aerospace", "defense", "3d printing", "smart cities",
        "infrastructure", "drones", "supply chain", "advanced manufacturing",
        "construction tech", "last mile delivery", "autonomous vehicles",
        "precision agriculture",
    ]},
    # Consumer
    **{t: "consumer & lifestyle" for t in [
        "wearable technology", "lifestyle", "luxury", "pet economy",
        "wellness", "beauty tech", "smart home", "plant-based",
        "direct-to-consumer", "athleisure", "connected fitness",
        "esports", "metaverse", "nft",
    ]},
    # Financial
    **{t: "financial services" for t in [
        "banking", "insurance", "real estate", "cryptocurrency", "defi",
        "asset management", "wealth management", "payments infrastructure",
        "embedded finance", "open banking", "credit scoring",
        "digital assets", "buy now pay later",
    ]},
    # Demographics
    **{t: "demographics & society" for t in [
        "aging population", "millennial consumer", "remote work",
        "gig economy", "urbanization", "diversity inclusion",
        "digital identity", "privacy",
    ]},
    # Materials
    **{t: "materials & resources" for t in [
        "lithium", "rare earth", "copper", "gold", "silver", "uranium",
        "steel", "aluminum", "cobalt", "nickel", "timber", "water resources",
    ]},
    # Agriculture
    **{t: "agriculture & food" for t in [
        "agriculture", "agtech", "vertical farming", "food safety",
        "food delivery", "alternative protein",
    ]},
    # Telecom
    **{t: "telecom & media" for t in [
        "telecommunications", "fiber optics", "satellite", "media",
        "music streaming", "podcasting", "digital advertising",
        "content moderation",
    ]},
    # Government
    **{t: "government & public sector" for t in [
        "govtech", "defense tech", "national security", "civic engagement",
    ]},
    # Cross-cutting
    **{t: "cross-cutting" for t in [
        "data center", "cloud infrastructure", "ai chips", "generative ai",
        "responsible ai", "climate tech", "impact investing", "femtech",
        "eldertech", "neurotechnology", "bioprinting", "nanotechnology",
        "photonics",
    ]},
}

ALL_THEMES: set[str] = set(THEME_DESCRIPTIONS.keys())
